### PR TITLE
Add otel logging to sdk

### PR DESCRIPTION
**Pull request by sterschl**

### CODE REVIEW

**Comment by tlanfer** [comment]
The implementation looks good, i like the API.

I am not sure about the tests. I think running all testcases against all log levels and all variants of tests messages is neat. But it took me a bit to understand how they work. Because of the indirection of using table driven tests, they dont follow the usual pattern of arrange/act/assert, or setup/invoke/assert. 

As an example, compare your test `TestLogMessageWithHttpRequestAndForwardedHeader_AddHttpPropertyAndWritesJSONToBuffer`
```golang

func TestLogMessageWithHttpRequestAndForwardedHeader_AddHttpPropertyAndWritesJSONToBuffer(t *testing.T) {
	req := httptest.NewRequest("GET", "https://www.example.com/path?q=param", nil)
	req.Header.Set("User-Agent", "Mozilla/5.0")
	req.Header.Set("X-Forwarded-For", "client, proxy1, proxy2")
	runTestcasesWithBuilder(t, log.WithHttpRequest(req), func(sev int) string {
		return fmt.Sprintf("{\"time\":\"2022-01-01T01:02:03.000000004Z\",\"sev\":%d,\"body\":\"This is a log message\",\"attr\":{\"http\":{\"method\":\"GET\",\"url\":\"https://www.example.com/path?q=param\",\"target\":\"/path?q=param\",\"host\":\"www.example.com\",\"scheme\":\"https\",\"route\":\"/path\",\"userAgent\":\"Mozilla/5.0\",\"clientIP\":\"client\"}}}\n", sev)
	})
}
```
with a minimal rewrite:
```golang
func TestLogMessageWithHttpRequestAndForwardedHeader_AddHttpPropertyAndWritesJSONToBuffer_Simple(t *testing.T) {
	// prepare the test environment
	rec := newOutputRecorder(t)

	req := httptest.NewRequest("GET", "https://www.example.com/path?q=param", nil)
	req.Header.Set("User-Agent", "Mozilla/5.0")
	req.Header.Set("X-Forwarded-For", "client, proxy1, proxy2")

	// execute your unit under test
	log.WithHttpRequest(req).Info(context.Background(), "This is a log message")

	// validate the results
	rec.OutputShouldBe(`{"time":"2022-01-01T01:02:03.000000004Z","sev":9,"body":"This is a log message","attr":{"http":{"method":"GET","url":"https://www.example.com/path?q=param","target":"/path?q=param","host":"www.example.com","scheme":"https","route":"/path","userAgent":"Mozilla/5.0","clientIP":"client"}}}` + "\n")
}
```

How much are you gaining from running all your tests table-driven, vs. having more specific tests for specific features.

**Comment by tlanfer** [comment]
The most extreme example of this indirection is obvious when you start calling the unit under test using reflection to dynamically select the correct method.

**Comment by sterschl** [comment]
Hi tlanfer, thanks for your feedback. I have adjusted the unittests and simplified them.

**Comment by tlanfer** [comment]
Looks good, i merged it 👍

**Pull request merged**
